#========================================
# 공통 Config
#========================================
# session-time은 Applcation.java에서 설정

server:
  port: 48080
  error:
    whitelabel:
      enabled: false
      
logging:
  level:
    root: INFO
    com.daou.ems: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%-5level] [%X{identity}] %msg %n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5level] [%X{identity}] %msg %n"
  file: "/log/setlist-admin/service.log"

spring:
  mvc:
    favicon:
      enabled: false
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  resources:
    static-locations:
      - "/webjars/**"
  redis:
    host: 123.123.123.123
    password: 123
    port: 6379
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: 
    initialize: true
    tomcat:
      max-active: 10
      max-idle: 5
      min-idle: 2
      max-wait: -1
      initial-size: 5
      remove-abandoned: true
      remove-abandoned-timeout: 60
      validation-query: SELECT 1
      test-on-return: true
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none

mybatis:
  executor-type: REUSE
  configuration:
    cache-enabled: false
    use-generated-keys: true
    map-underscore-to-camel-case: true
  type-handlers-package: org.apache.ibatis.type.LocalDateTimeTypeHandler
  type-aliases-package: com.daou.setlist.common.model, com.daou.setlist.admin.model
  mapper-locations:
    - "classpath:/com/daou/setlist/sqlmap/*.xml"
